name: Build

on: [push, pull_request]

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  CIBW_BUILD: cp3?-* pp3?-*

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel cibuildwheel twine
      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v1
        with:
          name: wheels
          path: ./wheelhouse
      - name: Upload to PyPI
        run: |
          python -m twine upload --verbose --skip-existing ./wheelhouse/*.whl
