name: Build

on: [push, pull_request]

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  CIBW_BUILD: cp3?-* pp3?-*

jobs:
  build_wheels:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    name: Build wheel (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel cibuildwheel
      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v1
        with:
          name: wheels
          path: ./wheelhouse

  publish_wheels:
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    needs: build_wheels

    name: Publish wheels

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install publish dependencies
        run: |
          python -m pip install twine
      - name: Upload to PyPI
        run: |
          python -m twine upload --verbose --skip-existing ./wheelhouse/*.whl